#!/bin/bash

sxhkd &

# initial desktops
bspc monitor eDP-1 -d term-1 pwn-1 web-1 vm-1 misc-1 term-2 pwn-2 web-2 vm-2 misc-2

# monitor 
# MUST be true otherwise the removed monitor will prevent moving the last
# desktop to primary monitor
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


# setup monitors
. /home/motoko/.config/bspwm/multimonitor_setup.sh


# setup colors
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')


# global border/gap
bspc config border_width  2
bspc config window_gap    8
bspc config split_ratio   0.50

# border color
bspc config focused_border_color   "#EF626C"
bspc config normal_border_color    "#93B7BE"
bspc config active_border_color    "#F1AB86"
bspc config presel_feedback_color  "#EF626C"


bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  false
bspc config single_monocle       false


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


